name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  
  # Manual Trigger: Allows you or Arwa to run the suite manually from GitHub UI
  workflow_dispatch:

  # Scheduled Trigger: Runs automatically every Monday at 6:00 AM UTC
  schedule:
    - cron: '0 6 * * 1'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npx playwright test
      
    # ALLURE STEP 1: Compiles the test data from allure-results into the final HTML dashboard
    - name: Generate Allure Report
      if: always()
      run: npx allure generate allure-results --clean -o allure-report
      
    # ALLURE STEP 2: Uploads the compiled Allure report so the team can download it
    - name: Upload Allure Report Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report-dashboard
        path: allure-report/
        retention-days: 30